import LazyClass from './core/lazy';
const a =
  'sadsadsadasdsadasdsadsadsadsadasdsadasdsadsadsadsadasdsadasdsadsadsadsadasdsadasdsadsadsadsadasdsadasdsadsadsadsadasdsadasdsadsadsadsadasdsadasdsadsadsadsadasdsadasdsadsadsadsadasdsadasdsadsadsadsadasdsadasdsadsadsadsadasdsadasdsadsadsadsadasdsadasdsad, sadsadsadasdsadasdsadsadsadsadasdsadasdsadsadsadsadasdsadasdsadsadsadsadasdsadasdsadsadsadsadasdsadasdsadsadsadsadasdsadasdsadsadsadsadasdsadasdsadsadsadsadasdsadasdsadsadsadsadasdsadasdsadsadsadsadasdsadasdsadsadsadsadasdsadasdsadsadsadsadasdsadasdsad';
export default {
  install() {}
};
